home/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'home'

urlpatterns = [
    path('' , views.home , name='home') , 
    
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('' , views.productlist , name='product_list') , 
    path('<slug:category_slug>' , views.productlist , name='product_list_category') , 
    path('detail/<slug:product_slug>' , views.productdetail , name='product_detail')
]

resale/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from home import views as home_views
from itempost import views as item_views
from product import views as product_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^$',home_views.index,name='home_page'),
    url('home/',include('home.urls',namespace='home')),
    path('accounts/', include('allauth.urls')), # allauth url
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    url('product/',include('product.urls', namespace='products')),
    url('itempost/',item_views.item_post,name='item_post'),


    path('contact/',home_views.contact,name='contact'),
    path('contact/',home_views.contact,name='contact'),
    path('faq/',home_views.faq,name='faq'),
    path('feedback/',home_views.feedback,name='feedback'),
    path('howitworks/',home_views.howitworks,name='howitworks'),
    path('privacy/',home_views.privacy,name='privacy'),

    url('home/category/(?P<cate>.+)/$',home_views.category_page,name='category_page'),
    url('home/item/(?P<item>.+)/$',home_views.single_item,name='single_item'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
# Create your models here.

class Product(models.Model):

    CONDITION_TYPE = (
        ("New" , "New") ,
        ("Used" , "Used")
    )

    ## contain all the products informations
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User , on_delete=models.CASCADE)
    description = models.TextField(max_length=500)
    condition = models.CharField(max_length=100 , choices=CONDITION_TYPE)
    category = models.ForeignKey('Category' , on_delete=models.SET_NULL , null=True)
    brand = models.ForeignKey('Brand' , on_delete=models.SET_NULL , null=True)
    price = models.DecimalField(max_digits=10,decimal_places=5)
    image = models.ImageField(upload_to='main_product/' , blank=True , null=True)
    created = models.DateTimeField(default=timezone.now)

    slug = models.SlugField(blank=True  , null=True)


    def save(self , *args , **kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Product , self).save(*args , **kwargs)


    def __str__(self):
        return self.name



class ProductImages(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/' , blank=True , null=True)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'




class Category(models.Model):
    ## for product category
    category_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category/' , blank=True , null=True)

    slug = models.SlugField(blank=True  , null=True)


    def save(self , *args , **kwargs):
        if not self.slug and self.category_name :
            self.slug = slugify(self.category_name)
        super(Category , self).save(*args , **kwargs)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name



class Brand(models.Model):
    ## for product brand
    brand_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.brand_name

product/views.py
from django.shortcuts import render
from .models import Product , ProductImages , Category
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import Q
from django.shortcuts import get_object_or_404
# Create your views here.


def productlist(request , category_slug=None):
    category = None
    productlist = Product.objects.all()
    categorylist = Category.objects.annotate(total_products=Count('product'))

    if category_slug :
        category = get_object_or_404(Category ,slug=category_slug)
        productlist = productlist.filter(category=category)

    search_query = request.GET.get('q')
    if search_query :
        productlist = productlist.filter(
            Q(name__icontains = search_query) |
            Q(description__icontains = search_query)|
            Q(condition__icontains = search_query)|
            Q(brand__brand_name__icontains = search_query) |
            Q(category__category_name__icontains = search_query) 
        )

    paginator = Paginator(productlist, 1) # Show 25 contacts per page
    page = request.GET.get('page')
    productlist = paginator.get_page(page)
    template = 'product/product_list.html'

    context = {'product_list' : productlist , 'category_list' : categorylist ,'category' : category }
    return render(request , template , context)




def productdetail(request , product_slug):
    print(product_slug)
    products=Product.objects.all()
    productdetail = Product.objects.get(slug=product_slug)
    productimages = ProductImages.objects.filter(product=productdetail)
    template = 'product/product_detail.html'
    context = {'product_detail' : productdetail , 'product_images' : productimages,'products':products}
    return render(request , template , context)

templates/product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<ol class="breadcrumb" style="margin-bottom: 5px;">
				<li><a href="/">Home</a></li>
				<li><a href="{% url 'products:product_list' %}">All Ads</a></li>
				<li class="active">Mobile Phone</li>
			</ol>
			<div class="product-desc">
				<div class="col-md-7 product-view">
					<h2>{{product_detail.name}}</h2>
					<p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">state</a>, <a href="#">city</a>| Added at {{product_detail.created}}, Ad ID: 987654321</p>
					<div class="flexslider">
						<ul class="slides">
                            
                            {% for image in product_images %}
                                                        
                                <li data-thumb="{{image.image.url}}">
                                    <img src="{{image.image.url}}" />
                                </li>

                            {% endfor %}
						</ul>
					</div>
					<!-- FlexSlider -->
					  <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
					<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4>Brand : <a href="#">{{product_detail.brand}}</a></h4>
						<h4>Views : <strong>150</strong></h4>
						<p><strong>Summary</strong> {{product_detail.description}}</p>
					
					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">$ {{product_detail.price}}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{product_detail.condition}}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{product_detail.category}}</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						<p><i class="glyphicon glyphicon-earphone"></i>00-85-9875462655</p>
					</div>
						<div class="tips">
						<h4>Safety Tips for Buyers</h4>
							<ol>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
							</ol>
						</div>
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--//single-page-->

{% endblock body %}

templates/product/product_list.html
{% extends 'base.html' %}

{% block body %}

<!-- Products -->
<div class="total-ads main-grid-border">
	<div class="container">
		<br>
		<div class="all-categories">
			<h3> Select your category and find the perfect ad</h3>
			<ul class="all-cat-list">

				{% for category in category_list %}
				<li><a href="{% url 'category_page' category %}">{{category}} <span
							class="num-of-ads">({{category.total_products}})</span></a></li>
				{% endfor %}
			</ul>
		</div>
		<ol class="breadcrumb" style="margin-bottom: 5px;">
			<li><a href="/">Home</a></li>
			<li class="active"> <a href="{% url 'products:product_list' %}"> All Ads </a></li>
			{% if category %}
			<li class="active">{{category}}</li>
			{% endif %}

		</ol>
		<div class="ads-grid">
			<div class="side-bar col-md-3">
				<div class="search-hotel">
					<h3 class="sear-head">Search</h3>
					<form method="GET" action="{% url 'products:product_list' %}">
						<input type="text" placeholder="Product name..." name="q" required="">
						<input type="submit" value=" ">
					</form>
				</div>

				<div class="featured-ads">
					<h2 class="sear-head fer">Featured Ads</h2>
					<div class="featured-ad">
						<a href="single.html">
							<div class="featured-ad-left">
								<img src="images/f1.jpg" title="ad image" alt="" />
							</div>
							<div class="featured-ad-right">
								<h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
								<p>$ 450</p>
							</div>
							<div class="clearfix"></div>
						</a>
					</div>
					<div class="featured-ad">
						<a href="single.html">
							<div class="featured-ad-left">
								<img src="images/f2.jpg" title="ad image" alt="" />
							</div>
							<div class="featured-ad-right">
								<h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
								<p>$ 380</p>
							</div>
							<div class="clearfix"></div>
						</a>
					</div>
					<div class="featured-ad">
						<a href="single.html">
							<div class="featured-ad-left">
								<img src="images/f3.jpg" title="ad image" alt="" />
							</div>
							<div class="featured-ad-right">
								<h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
								<p>$ 560</p>
							</div>
							<div class="clearfix"></div>
						</a>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="ads-display col-md-9">
				<div class="wrapper">
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
						<div id="myTabContent" class="tab-content">
							<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
								<div>
									<div id="container">

										<div class="clearfix"></div>
										<ul class="list">


											{% for product in products %}
											<div class="card mb-3" style="min-width: 540px;">
												<div class="row no-gutters">
													<div class="col-md-4">
														<img src="/media/{{ product.image }}" class="card-img"
															alt="...">
													</div>
													<div class="col-md-8">
														<div class="card-body">
															<a class="card-title"
																href="{% url 'single_item' product.name %}">Product Name
																:{{ product.name }}</a>
															<p class="card-text">Description : {{ product.description }}
															</p>
															<p class="card-text">Price :
																<strong>{{ product.price }}</strong></p>
														</div>
													</div>
												</div>
											</div>
											<br>

											{% endfor %}


											{% for product in product_list %}
											<a href="{% url 'products:product_detail' product.slug %}">
												<li>
													<img src="{{product.image.url}}" title="" alt="" />
													<section class="list-left">
														<h5 class="title">{{product.name}}</h5>
														<span class="adprice">${{product.price}}</span>
														<p class="catpath">Mobile Phones » {{product.brand}}</p>
													</section>
													<section class="list-right">
														<span class="date">Date, {{product.created}}</span>
														<span class="cityname">City name</span>
													</section>
													<div class="clearfix"></div>
												</li>
											</a>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>

							{% if product_list.has_other_pages %}

							<ul class="pagination pagination-sm">
								{% if product_list.has_previous %}
								<li><a href="?page={{ product_list.previous_page_number }}">Prev</a></li>
								{% else %}
								<li class="disabled"></li>
								{% endif %}

								{% for pages in product_list.paginator.page_range %}
								{% if product_list.number == pages %}
								<li><a href="#">{{pages}}</a></li>
								{% else %}
								<li><a href="?page={{pages}}">{{pages}}</a></li>
								{% endif %}

								{% endfor %}


								{% if product_list.has_next %}
								<li><a href="?page={{ product_list.next_page_number }}">Next</a></li>
								{% else %}
								<li class="disabled"></li>
								{% endif %}

							</ul>

							{% endif %}
						</div>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!-- // Products -->

{% endblock body %}